import { supabase, supabaseConfigured } from './lib/supabase.js'

let resources = [
  { id: 1, name: '校园安全教育主题班会', category: '视频', type: 'MP4', size: '42.8 MB', downloads: 743, author: '德育处', date: '2025-02-13', icon: '🎬', description: '校园安全主题班会视频资源，适合班级教育和家校共育场景。' },
  { id: 2, name: '课堂教学示范视频', category: '视频', type: 'MP4', size: '28.4 MB', downloads: 402, author: '教研组', date: '2025-02-10', icon: '🎬', description: '课堂教学示范视频。' },
]
const state = { query: '', sort: '最新上传', page: 1, pageSize: 5, selected: null, auth: false, authMode: 'login', uploading: false, user: null, role: 'user', message: '' }
const app = document.querySelector('#app'); const number = n => Number(n || 0).toLocaleString('zh-CN')
const iconFor = () => '🎬'

async function loadResources() {
  if (!supabaseConfigured) return
  const { data, error } = await supabase.from('resources').select('*').eq('status', 'published').eq('category', '视频').order('created_at', { ascending: false })
  if (error) { console.warn('Supabase 资源读取失败，将使用演示数据：', error.message); return }
  if (data?.length) resources = data.map(r => ({ id: r.id, name: r.title, category: '视频', type: r.file_type || 'MP4', size: r.file_size ? `${(r.file_size / 1024 / 1024).toFixed(1)} MB` : '—', downloads: r.download_count, author: '管理员', date: r.created_at.slice(0, 10), icon: iconFor(), description: r.description, filePath: r.file_path }))
}
async function loadSession() {
  if (!supabaseConfigured) return
  const { data } = await supabase.auth.getSession(); state.user = data.session?.user || null
  if (state.user) { const profile = await supabase.from('profiles').select('role').eq('id', state.user.id).maybeSingle(); state.role = profile.data?.role || 'user' }
  supabase.auth.onAuthStateChange(() => { loadSession().then(render) })
}
function filtered() { const q = state.query.toLowerCase(); return resources.filter(r => !q || `${r.name} ${r.description}`.toLowerCase().includes(q)).sort((a,b) => state.sort === '最多播放' ? b.downloads-a.downloads : b.date.localeCompare(a.date)) }
function stat(label, value, icon) { return `<div class="stat-card"><div><div class="stat-label">${label}</div><div class="stat-value">${value}</div></div><div class="stat-icon">${icon}</div></div>` }
function resourceCard(r) { return `<article class="resource"><div class="resource-icon">${r.icon}</div><div><h3 class="resource-name">${r.name}</h3><div class="resource-meta">视频 · ${r.type} · ${r.size} · ${number(r.downloads)} 次播放</div></div><div class="resource-actions"><button class="download" data-detail="${r.id}">在线观看</button></div></article>` }
function authModal() { return `<div class="modal-backdrop" data-auth-close><div class="modal"><div class="modal-head"><div><h2>${state.authMode === 'login' ? '登录' : '注册'}</h2><div class="resource-meta">使用邮箱访问知源资源库</div></div><button class="close" data-auth-close>×</button></div><form id="auth-form"><label class="form-label">邮箱<input class="form-input" name="email" type="email" required placeholder="you@example.com" /></label><label class="form-label">密码<input class="form-input" name="password" type="password" minlength="6" required placeholder="至少 6 位字符" /></label><div id="auth-status" class="form-status">${state.message}</div><button class="primary" type="submit">${state.authMode === 'login' ? '登录' : '注册'}</button></form><button class="link auth-switch" data-auth-switch>${state.authMode === 'login' ? '还没有账号？注册' : '已有账号？登录'}</button></div></div>` }
function uploadModal() { return `<div class="modal-backdrop" data-upload-close><div class="modal"><div class="modal-head"><div><h2>上传视频</h2><div class="resource-meta">仅管理员可以上传，上传后进入待审核状态</div></div><button class="close" data-upload-close>×</button></div><form id="upload-form"><label class="form-label">视频名称<input class="form-input" name="title" required maxlength="100" placeholder="例如：课堂教学示范视频" /></label><label class="form-label">视频描述<textarea class="form-input" name="description" rows="3" maxlength="500"></textarea></label><label class="form-label">选择视频<input class="form-input" name="file" type="file" required accept="video/mp4,video/webm,video/ogg" /><span class="form-hint">仅支持 MP4、WebM、Ogg，单个文件最大 200 MB。</span></label><div id="upload-status" class="form-status"></div><button class="primary" type="submit">开始上传</button></form></div></div>` }
async function authSubmit(form) { if (!supabaseConfigured) throw new Error('Supabase 尚未配置'); const email=form.email.value.trim(), password=form.password.value; const result = state.authMode === 'login' ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password }); if (result.error) throw result.error; state.message = state.authMode === 'login' ? '登录成功' : '注册成功，请检查邮箱确认后再登录'; if (state.authMode === 'login') { state.auth=false; await loadSession() } render() }
async function uploadVideo(form) { if (!state.user || state.role !== 'admin') throw new Error('只有管理员可以上传视频'); const file=form.file.files[0]; if (!file || !file.type.startsWith('video/')) throw new Error('请选择视频文件'); if (file.size > 200*1024*1024) throw new Error('视频不能超过 200 MB'); const path=`${state.user.id}/${crypto.randomUUID()}-${file.name.replace(/[^\w.\-一-龥]/g,'_')}`; const status=document.querySelector('#upload-status'); status.textContent='正在上传视频…'; const uploaded=await supabase.storage.from('resource-files').upload(path,file,{contentType:file.type,upsert:false}); if(uploaded.error) throw uploaded.error; const inserted=await supabase.from('resources').insert({title:form.title.value.trim(),description:form.description.value.trim(),category:'视频',file_path:path,file_type:file.name.split('.').pop()?.toUpperCase()||'MP4',file_size:file.size,author_id:state.user.id,status:'pending'}); if(inserted.error){await supabase.storage.from('resource-files').remove([path]);throw inserted.error} status.textContent='上传成功，等待管理员审核。'; form.querySelector('button[type=submit]').disabled=true }
async function detailModal(r) { let media=''; if(r.filePath && supabaseConfigured){ const signed=await supabase.storage.from('resource-files').createSignedUrl(r.filePath,600); if(!signed.error) media=`<video class="video-player" controls controlsList="nodownload" oncontextmenu="return false" src="${signed.data.signedUrl}"></video>` } return `<div class="modal-backdrop" data-close><div class="modal"><div class="modal-head"><div><h2>🎬 ${r.name}</h2><div class="resource-meta">上传者：${r.author} · 更新于 ${r.date}</div></div><button class="close" data-close>×</button></div>${media || '<div class="video-placeholder">视频审核后可在线观看</div>'}<p>${r.description}</p><div class="detail-grid"><div class="detail-item"><b>视频格式</b>${r.type}</div><div class="detail-item"><b>视频大小</b>${r.size}</div><div class="detail-item"><b>播放次数</b>${number(r.downloads)}</div><div class="detail-item"><b>访问方式</b>仅在线播放</div></div></div></div>` }
async function openDetail(r) { state.selected = r; render(); const modal=document.querySelector('.modal'); if(modal && r.filePath){ const html=await detailModal(r); const holder=document.createElement('div'); holder.innerHTML=html; document.querySelector('.modal-backdrop')?.replaceWith(holder.firstElementChild); bindEvents() } }
async function render() { const result=filtered(), total=Math.max(1,Math.ceil(result.length/state.pageSize)); state.page=Math.min(state.page,total); const items=result.slice((state.page-1)*state.pageSize,state.page*state.pageSize); app.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">知</div><span>知源视频库</span></div><nav class="nav"><button class="active"><span class="icon">⌂</span><span>工作台</span></button><button><span class="icon">▤</span><span>视频中心</span></button><button><span class="icon">?</span><span>使用帮助</span></button></nav><div class="sidebar-foot">优质视频资源<br/>在线分享与学习</div></aside><main class="main"><header class="topbar"><div class="breadcrumb">首页 / <b>工作台</b></div><div class="user-area">${state.user ? `<span>${state.user.email}</span><button class="link" data-logout>退出</button>` : '<span>访客模式</span><button class="link" data-auth>登录 / 注册</button>'}<div class="avatar">知</div></div></header><section class="content"><div class="welcome"><div><h1>欢迎来到知源视频库 👋</h1><div class="subtitle">资源仅支持在线播放，不提供视频下载</div></div>${state.role==='admin' ? '<button class="primary" data-upload>＋ 上传视频</button>' : ''}</div><div class="stats">${stat('视频总数',number(resources.length),'▶')}${stat('累计播放',number(resources.reduce((a,r)=>a+r.downloads,0)),'◉')}${stat('当前身份',state.role==='admin'?'管理员':'普通用户','♙')}${stat('访问方式','在线播放','▣')}</div><div class="layout"><div class="panel"><div class="panel-title"><h2>视频资源</h2><span class="resource-meta">${state.role==='admin'?'管理员可上传':'登录后可继续使用'}</span></div><div class="toolbar"><input class="search" id="search" value="${state.query}" placeholder="搜索视频名称或描述..."/><select id="sort"><option ${state.sort==='最新上传'?'selected':''}>最新上传</option><option ${state.sort==='最多播放'?'selected':''}>最多播放</option></select></div><div>${items.length?items.map(resourceCard).join(''):'<div class="empty">暂无视频资源。</div>'}</div><div class="pagination">${Array.from({length:total},(_,i)=>`<button class="page ${i+1===state.page?'current':''}" data-page="${i+1}">${i+1}</button>`).join('')}</div></div><aside><div class="panel"><div class="panel-title"><h2>使用说明</h2></div><div class="activity"><div class="activity-item"><span class="dot"></span><div>普通用户可以注册、登录并在线观看已审核视频。</div></div><div class="activity-item"><span class="dot" style="background:#ffba58"></span><div>只有管理员账号显示上传入口。</div></div><div class="activity-item"><span class="dot" style="background:#9b8af7"></span><div>视频不提供下载按钮，仅限在线播放。</div></div></div></div></aside></div></section></main></div>${state.auth?authModal():''}${state.uploading?uploadModal():''}${state.selected?await detailModal(state.selected):''}`; bindEvents() }
function bindEvents() { document.querySelector('#search')?.addEventListener('input',e=>{state.query=e.target.value;state.page=1;render()}); document.querySelector('#sort')?.addEventListener('change',e=>{state.sort=e.target.value;state.page=1;render()}); document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>{state.page=+b.dataset.page;render()})); document.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>openDetail(resources.find(r=>String(r.id)===b.dataset.detail)))); document.querySelector('[data-auth]')?.addEventListener('click',()=>{state.auth=true;state.authMode='login';state.message='';render()}); document.querySelector('[data-logout]')?.addEventListener('click',async()=>{await supabase.auth.signOut();state.user=null;state.role='user';render()}); document.querySelectorAll('[data-auth-close]').forEach(e=>e.addEventListener('click',x=>{if(x.target===e||e.classList.contains('close')){state.auth=false;render()}})); document.querySelector('[data-auth-switch]')?.addEventListener('click',()=>{state.authMode=state.authMode==='login'?'signup':'login';state.message='';render()}); document.querySelector('#auth-form')?.addEventListener('submit',async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button[type=submit]');const status=document.querySelector('#auth-status');b.disabled=true;try{await authSubmit(e.currentTarget)}catch(error){status.textContent=`操作失败：${error.message}`;b.disabled=false}}); document.querySelector('[data-upload]')?.addEventListener('click',()=>{state.uploading=true;render()}); document.querySelectorAll('[data-upload-close]').forEach(e=>e.addEventListener('click',x=>{if(x.target===e||e.classList.contains('close')){state.uploading=false;render()}})); document.querySelector('#upload-form')?.addEventListener('submit',async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button[type=submit]');const s=document.querySelector('#upload-status');b.disabled=true;try{await uploadVideo(e.currentTarget)}catch(error){s.textContent=`上传失败：${error.message}`;b.disabled=false}}); document.querySelectorAll('[data-close]').forEach(e=>e.addEventListener('click',x=>{if(x.target===e||e.classList.contains('close')){state.selected=null;render()}})) }
async function boot(){ await loadResources(); await loadSession(); render() }
boot()
