import { supabase, supabaseConfigured } from './lib/supabase.js'

const demoVideos = [
  { id: 'demo-1', title: '校园安全教育主题班会', description: '校园安全主题班会视频，适合班级教育和家校共育。', type: 'MP4', size: '42.8 MB', date: '2025-02-13', views: 743 },
  { id: 'demo-2', title: '课堂教学示范视频', description: '课堂教学示范视频。', type: 'MP4', size: '28.4 MB', date: '2025-02-10', views: 402 }
]
const state = { videos: demoVideos, query: '', sort: 'latest', selected: null, user: null, role: 'user', modal: null, authMode: 'login', status: '', playerUrl: '' }
const app = document.querySelector('#app')

async function loadData() {
  if (!supabaseConfigured) return
  const session = await supabase.auth.getSession()
  state.user = session.data.session?.user || null
  if (state.user) {
    const profile = await supabase.from('profiles').select('role').eq('id', state.user.id).maybeSingle()
    state.role = profile.data?.role || 'user'
  }
  const result = await supabase.from('resources').select('*').eq('status', 'published').eq('category', '视频').order('created_at', { ascending: false })
  if (!result.error && result.data?.length) state.videos = result.data.map(item => ({ id: item.id, title: item.title, description: item.description, type: item.file_type || 'MP4', size: item.file_size ? `${(item.file_size / 1024 / 1024).toFixed(1)} MB` : '—', date: item.created_at.slice(0, 10), views: item.download_count || 0, filePath: item.file_path }))
}
function visibleVideos() {
  const query = state.query.trim().toLowerCase()
  return state.videos.filter(video => !query || `${video.title} ${video.description}`.toLowerCase().includes(query)).sort((a, b) => state.sort === 'views' ? b.views - a.views : b.date.localeCompare(a.date))
}
function authView() { return `<div class="overlay" data-close><section class="dialog" data-stop><button class="x" data-close>×</button><h2>${state.authMode === 'login' ? '登录' : '注册'}</h2><p class="muted">使用邮箱访问视频中心</p><form id="auth-form"><input name="email" type="email" required placeholder="邮箱"/><input name="password" type="password" minlength="6" required placeholder="密码（至少 6 位）"/><div class="status">${state.status}</div><button class="button primary" type="submit">${state.authMode === 'login' ? '登录' : '注册'}</button></form><button class="text-button" data-switch-auth>${state.authMode === 'login' ? '没有账号？注册' : '已有账号？登录'}</button></section></div>` }
function uploadView() { return `<div class="overlay" data-close><section class="dialog" data-stop><button class="x" data-close>×</button><h2>上传视频</h2><p class="muted">仅管理员可上传，审核通过后公开播放</p><form id="upload-form"><input name="title" required maxlength="100" placeholder="视频标题"/><textarea name="description" maxlength="500" placeholder="视频简介"></textarea><input name="file" type="file" required accept="video/mp4,video/webm,video/ogg"/><p class="hint">支持 MP4、WebM、Ogg，最大 200 MB。</p><div class="status">${state.status}</div><button class="button primary" type="submit">开始上传</button></form></section></div>` }
function playerView() { const video = state.selected; return `<div class="overlay" data-close><section class="dialog player-dialog" data-stop><button class="x" data-close>×</button><h2>${video.title}</h2><div class="player-wrap">${state.playerUrl ? `<video src="${state.playerUrl}" controls controlsList="nodownload" oncontextmenu="return false" autoplay></video>` : '<div class="player-loading">正在准备播放…</div>'}</div><p class="muted">${video.description || ''}</p><p class="hint">仅支持在线播放，不提供下载。</p></section></div>` }
function render() {
  const videos = visibleVideos()
  app.innerHTML = `<main class="video-center"><header class="header"><div class="logo"><span>知</span> 视频中心</div><div class="account">${state.user ? `<span>${state.user.email}</span><button class="text-button" data-logout>退出</button>` : '<button class="text-button" data-auth>登录 / 注册</button>'}${state.role === 'admin' ? '<button class="button primary small" data-upload>上传视频</button>' : ''}</div></header><section class="hero"><h1>视频中心</h1><p>打开即看，精选视频资源在线播放</p><div class="tools"><input id="search" value="${state.query}" placeholder="搜索视频…"/><select id="sort"><option value="latest" ${state.sort === 'latest' ? 'selected' : ''}>最新上传</option><option value="views" ${state.sort === 'views' ? 'selected' : ''}>最多播放</option></select></div></section><section class="video-list">${videos.length ? videos.map(video => `<button class="video-card" data-video="${video.id}"><span class="play">▶</span><span class="video-info"><b>${video.title}</b><small>${video.type} · ${video.size} · ${Number(video.views).toLocaleString()} 次播放</small><small>${video.description || ''}</small></span><span class="watch">在线观看 →</span></button>`).join('') : '<div class="empty">没有找到视频</div>'}</section><footer>知源视频中心 · 仅在线播放 · v2</footer></main>${state.modal === 'auth' ? authView() : ''}${state.modal === 'upload' ? uploadView() : ''}${state.modal === 'player' ? playerView() : ''}`
}
async function openPlayer(video) { state.selected = video; state.modal = 'player'; state.playerUrl = ''; render(); if (video.filePath && supabaseConfigured) { const result = await supabase.storage.from('resource-files').createSignedUrl(video.filePath, 600); if (!result.error) { state.playerUrl = result.data.signedUrl; render() } } }
async function submitAuth(form) { const email = form.email.value.trim(); const password = form.password.value; const result = state.authMode === 'login' ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password }); if (result.error) throw result.error; state.status = state.authMode === 'login' ? '' : '注册成功，请先确认邮箱'; if (state.authMode === 'login') { state.modal = null; await loadData() } render() }
async function submitUpload(form) { if (!state.user || state.role !== 'admin') throw new Error('只有管理员可以上传视频'); const file = form.file.files[0]; if (!file?.type.startsWith('video/')) throw new Error('请选择视频文件'); if (file.size > 200 * 1024 * 1024) throw new Error('视频不能超过 200 MB'); const path = `${state.user.id}/${crypto.randomUUID()}-${file.name.replace(/[^\w.\-一-龥]/g, '_')}`; state.status = '正在上传…'; render(); const upload = await supabase.storage.from('resource-files').upload(path, file, { contentType: file.type }); if (upload.error) throw upload.error; const insert = await supabase.from('resources').insert({ title: form.title.value.trim(), description: form.description.value.trim(), category: '视频', file_path: path, file_type: file.name.split('.').pop()?.toUpperCase() || 'MP4', file_size: file.size, author_id: state.user.id, status: 'pending' }); if (insert.error) { await supabase.storage.from('resource-files').remove([path]); throw insert.error } state.status = '上传成功，等待审核'; render() }
app.addEventListener('click', async event => { const target = event.target.closest('button, [data-video]'); if (!target) return; if (target.dataset.close !== undefined && !event.target.closest('[data-stop]')) { state.modal = null; render(); return } if (target.dataset.close !== undefined && target.classList.contains('x')) { state.modal = null; render(); return } if (target.dataset.video) { await openPlayer(state.videos.find(video => String(video.id) === target.dataset.video)); return } if (target.dataset.auth !== undefined) { state.modal = 'auth'; state.authMode = 'login'; state.status = ''; render(); return } if (target.dataset.switchAuth !== undefined) { state.authMode = state.authMode === 'login' ? 'signup' : 'login'; state.status = ''; render(); return } if (target.dataset.logout !== undefined) { await supabase.auth.signOut(); state.user = null; state.role = 'user'; render(); return } if (target.dataset.upload !== undefined) { state.modal = 'upload'; state.status = ''; render() }})
app.addEventListener('input', event => { if (event.target.id === 'search') { state.query = event.target.value; render() } })
app.addEventListener('change', event => { if (event.target.id === 'sort') { state.sort = event.target.value; render() } })
app.addEventListener('submit', async event => { event.preventDefault(); const form = event.target; const button = form.querySelector('button[type=submit]'); button.disabled = true; try { if (form.id === 'auth-form') await submitAuth(form); else await submitUpload(form) } catch (error) { state.status = `操作失败：${error.message}`; render() } })
loadData().then(render)
