import { supabase, supabaseConfigured } from './lib/supabase.js'

let resources = [
  { id: 1, name: '小学语文五年级下册精品课件', category: '课件', type: 'PPTX', size: '18.6 MB', downloads: 1280, author: '教研组', date: '2025-02-18', icon: '📘', description: '覆盖五年级下册重点课文的课堂课件，包含教学目标、课堂活动与课后练习。', tags: ['语文', '五年级', '课件'] },
  { id: 2, name: '初中数学几何专题复习资料', category: '教案', type: 'PDF', size: '6.2 MB', downloads: 956, author: '陈老师', date: '2025-02-16', icon: '📐', description: '整理平面几何核心知识点与典型例题，适合复习课和专题训练使用。', tags: ['数学', '初中', '复习'] },
  { id: 3, name: '校园安全教育主题班会', category: '视频', type: 'MP4', size: '42.8 MB', downloads: 743, author: '德育处', date: '2025-02-13', icon: '🎬', description: '校园安全主题班会视频资源，适合班级教育和家校共育场景。', tags: ['安全教育', '班会'] },
  { id: 4, name: '英语自然拼读互动练习', category: '练习', type: 'DOCX', size: '3.8 MB', downloads: 621, author: '英语教研组', date: '2025-02-10', icon: '🔤', description: '适合低年级学生的自然拼读练习单，配套课堂互动环节。', tags: ['英语', '低年级', '练习'] },
  { id: 5, name: '教师公开课评价量表', category: '表格', type: 'XLSX', size: '1.1 MB', downloads: 488, author: '平台管理员', date: '2025-02-08', icon: '📊', description: '公开课听评课通用评价量表，支持按课堂环节进行记录。', tags: ['评价', '表格', '教研'] },
  { id: 6, name: '小学科学实验活动手册', category: '教案', type: 'PDF', size: '12.4 MB', downloads: 402, author: '科学组', date: '2025-02-04', icon: '🧪', description: '汇总常见小学科学实验的材料清单、步骤和安全提示。', tags: ['科学', '实验', '小学'] },
  { id: 7, name: '班主任工作计划模板', category: '表格', type: 'DOCX', size: '0.8 MB', downloads: 366, author: '王老师', date: '2025-01-28', icon: '🗓️', description: '可编辑的学期班主任工作计划模板，包含月度工作安排。', tags: ['班主任', '模板'] },
  { id: 8, name: '音乐课堂节奏训练素材', category: '音频', type: 'MP3', size: '24.2 MB', downloads: 255, author: '音乐组', date: '2025-01-24', icon: '🎵', description: '适用于小学音乐课堂的节奏训练音频素材包。', tags: ['音乐', '素材'] },
]
const state = { query: '', category: '全部分类', sort: '最新上传', page: 1, pageSize: 5, favorites: JSON.parse(localStorage.getItem('resource-favorites') || '[]'), selected: null, uploading: false, user: null, loading: true }
const app = document.querySelector('#app'); let categories = ['全部分类']; const number = value => value.toLocaleString('zh-CN')
const iconFor = category => ({课件:'📘',教案:'📐',视频:'🎬',练习:'🔤',表格:'📊',音频:'🎵'}[category] || '📄')
async function loadResources() {
  if (!supabaseConfigured) return
  const { data, error } = await supabase.from('resources').select('*').eq('status', 'published').order('created_at', { ascending: false })
  if (error) { console.warn('Supabase 资源读取失败，将使用演示数据：', error.message); return }
  if (data?.length) resources = data.map(r => ({ id: r.id, name: r.title, category: r.category, type: r.file_type || 'FILE', size: r.file_size ? `${(r.file_size / 1024 / 1024).toFixed(1)} MB` : '—', downloads: r.download_count || 0, author: '资源贡献者', date: r.created_at.slice(0, 10), icon: iconFor(r.category), description: r.description, tags: [r.category], filePath: r.file_path }))
}
async function loadSession() { if (supabaseConfigured) { const { data } = await supabase.auth.getSession(); state.user = data.session?.user || null } }
async function boot() { await loadResources(); await loadSession(); categories = ['全部分类', ...new Set(resources.map(r => r.category))]; state.loading = false; render() }
function filteredResources() { const q = state.query.trim().toLowerCase(); let result = resources.filter(r => (state.category === '全部分类' || r.category === state.category) && (!q || `${r.name} ${r.category} ${r.author} ${r.tags.join(' ')}`.toLowerCase().includes(q))); return [...result].sort((a,b) => state.sort === '最多下载' ? b.downloads-a.downloads : b.date.localeCompare(a.date)) }
function statCard(label, value, icon) { return `<div class="stat-card"><div><div class="stat-label">${label}</div><div class="stat-value">${value}</div></div><div class="stat-icon">${icon}</div></div>` }
function resourceCard(r) { const fav = state.favorites.includes(r.id); return `<article class="resource"><div class="resource-icon">${r.icon}</div><div><h3 class="resource-name">${r.name}</h3><div class="resource-meta">${r.category} · ${r.type} · ${r.size} · ${number(r.downloads)} 次下载</div></div><div class="resource-actions"><button class="favorite ${fav?'active':''}" data-favorite="${r.id}">${fav?'★':'☆'}</button><button class="download" data-detail="${r.id}">查看</button></div></article>` }
function detailModal(r) { return `<div class="modal-backdrop" data-close><div class="modal"><div class="modal-head"><div><h2>${r.icon} ${r.name}</h2><div class="resource-meta">上传者：${r.author} · 更新于 ${r.date}</div></div><button class="close" data-close>×</button></div><p>${r.description}</p><div class="detail-grid"><div class="detail-item"><b>文件类型</b>${r.type}</div><div class="detail-item"><b>文件大小</b>${r.size}</div><div class="detail-item"><b>下载次数</b>${number(r.downloads)}</div><div class="detail-item"><b>资源分类</b>${r.category}</div></div><button class="primary" data-download="${r.id}">↓ 下载资源</button></div></div>` }
function render() { const result=filteredResources(), total=Math.max(1,Math.ceil(result.length/state.pageSize)); state.page=Math.min(state.page,total); const items=result.slice((state.page-1)*state.pageSize,state.page*state.pageSize); app.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">知</div><span>知源资源库</span></div><nav class="nav"><button class="active"><span class="icon">⌂</span><span>工作台</span></button><button><span class="icon">▤</span><span>资源中心</span></button><button><span class="icon">☆</span><span>我的收藏</span></button><button><span class="icon">?</span><span>使用帮助</span></button></nav><div class="sidebar-foot">让优质资源<br/>流动起来 · 共享知识</div></aside><main class="main"><header class="topbar"><div class="breadcrumb">首页 / <b>工作台</b></div><div class="user-area"><span>${state.user ? `已登录：${state.user.email}` : '访客模式'}</span><div class="avatar">知</div></div></header><section class="content"><div class="welcome"><div><h1>早上好，欢迎来到知源 👋</h1><div class="subtitle">发现、整理和分享有价值的教学资源</div></div><button class="primary" data-upload>＋ 上传资源</button></div><div class="stats">${statCard('资源总数',number(resources.length),'▤')}${statCard('累计下载',number(resources.reduce((a,r)=>a+r.downloads,0)),'↓')}${statCard('本周新增','12','✦')}${statCard('我的收藏',number(state.favorites.length),'☆')}</div><div class="layout"><div class="panel"><div class="panel-title"><h2>最近更新</h2><button class="link" data-all>查看全部 →</button></div><div class="toolbar"><input class="search" id="search" value="${state.query}" placeholder="搜索资源名称、分类或作者..."/><select id="category">${categories.map(c=>`<option ${c===state.category?'selected':''}>${c}</option>`).join('')}</select><select id="sort"><option ${state.sort==='最新上传'?'selected':''}>最新上传</option><option ${state.sort==='最多下载'?'selected':''}>最多下载</option></select></div><div>${items.length?items.map(resourceCard).join(''):'<div class="empty">没有找到匹配的资源，试试其他关键词。</div>'}</div><div class="pagination">${Array.from({length:total},(_,i)=>`<button class="page ${i+1===state.page?'current':''}" data-page="${i+1}">${i+1}</button>`).join('')}</div></div><aside><div class="panel"><div class="panel-title"><h2>热门分类</h2></div><div class="tags">${categories.slice(1).map(c=>`<button class="tag" data-category="${c}">${c}</button>`).join('')}</div></div><div class="panel"><div class="panel-title"><h2>平台动态</h2><button class="link">更多</button></div><div class="activity"><div class="activity-item"><span class="dot"></span><div>平台新增了 <b>12</b> 个精选资源<span class="time">今天 09:30</span></div></div><div class="activity-item"><span class="dot" style="background:#ffba58"></span><div>资源《数学几何专题》被下载 <b>100+</b> 次<span class="time">昨天 16:20</span></div></div><div class="activity-item"><span class="dot" style="background:#9b8af7"></span><div>欢迎参与资源共建<span class="time">2025-02-12</span></div></div></div></div></aside></div></section></main></div>${state.selected?detailModal(state.selected):''}${state.uploading?uploadModal():''}`; bindEvents() }
function uploadModal() { return `<div class="modal-backdrop" data-upload-close><div class="modal"><div class="modal-head"><div><h2>上传资源</h2><div class="resource-meta">上传后将进入待审核状态</div></div><button class="close" data-upload-close>×</button></div><form id="upload-form"><label class="form-label">资源名称<input class="form-input" name="title" required maxlength="100" placeholder="例如：小学科学实验活动手册" /></label><label class="form-label">资源分类<select class="form-input" name="category" required>${categories.slice(1).map(c=>`<option>${c}</option>`).join('')}<option>其他</option></select></label><label class="form-label">资源描述<textarea class="form-input" name="description" rows="3" maxlength="500" placeholder="简单介绍资源内容"></textarea></label><label class="form-label">选择文件<input class="form-input" name="file" type="file" required accept=".pdf,.ppt,.pptx,.doc,.docx,.xls,.xlsx,.zip,.mp4,.mp3,.png,.jpg,.jpeg" /><span class="form-hint">支持 PDF、Office、压缩包、音视频和图片，单个文件最大 50 MB。</span></label><div id="upload-status" class="form-status"></div><button class="primary" type="submit">开始上传</button></form></div></div>` }
async function uploadResource(form) { if (!supabaseConfigured) throw new Error('Supabase 尚未配置'); const { data: sessionData } = await supabase.auth.getSession(); const user = sessionData.session?.user; if (!user) throw new Error('请先登录 Supabase 账号后再上传'); const file = form.file.files[0]; if (!file) throw new Error('请选择文件'); if (file.size > 50 * 1024 * 1024) throw new Error('文件不能超过 50 MB'); const safeName = file.name.replace(/[^\\w.\\-一-龥]/g, '_'); const filePath = `${user.id}/${crypto.randomUUID()}-${safeName}`; const status = document.querySelector('#upload-status'); status.textContent = '正在上传文件…'; const { error: uploadError } = await supabase.storage.from('resource-files').upload(filePath, file, { contentType: file.type || 'application/octet-stream', upsert: false }); if (uploadError) throw uploadError; status.textContent = '文件已上传，正在保存资源信息…'; const { error: insertError } = await supabase.from('resources').insert({ title: form.title.value.trim(), category: form.category.value, description: form.description.value.trim(), file_path: filePath, file_type: file.name.split('.').pop()?.toUpperCase() || 'FILE', file_size: file.size, author_id: user.id, status: 'pending' }); if (insertError) { await supabase.storage.from('resource-files').remove([filePath]); throw insertError } status.textContent = '上传成功，等待管理员审核。'; form.querySelector('button[type="submit"]').disabled = true }
function bindEvents() { document.querySelector('#search')?.addEventListener('input',e=>{state.query=e.target.value;state.page=1;render()}); document.querySelector('[data-upload]')?.addEventListener('click',()=>{state.uploading=true;render()}); document.querySelectorAll('[data-upload-close]').forEach(e=>e.addEventListener('click',event=>{if(event.target===e||e.classList.contains('close')){state.uploading=false;render()}})); document.querySelector('#upload-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const button=form.querySelector('button[type="submit"]');button.disabled=true;try{await uploadResource(form)}catch(error){const status=document.querySelector('#upload-status');status.textContent=`上传失败：${error.message}`;button.disabled=false}}); document.querySelector('#category')?.addEventListener('change',e=>{state.category=e.target.value;state.page=1;render()}); document.querySelector('#sort')?.addEventListener('change',e=>{state.sort=e.target.value;state.page=1;render()}); document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>{state.page=+b.dataset.page;render()})); document.querySelectorAll('[data-favorite]').forEach(b=>b.addEventListener('click',()=>{const id=+b.dataset.favorite;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];localStorage.setItem('resource-favorites',JSON.stringify(state.favorites));render()})); document.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>{state.selected=resources.find(r=>r.id===+b.dataset.detail);render()})); document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.category;state.page=1;render()})); document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',e=>{if(e.target===b||b.classList.contains('close')){state.selected=null;render()}})); document.querySelectorAll('[data-download]').forEach(b=>b.addEventListener('click',()=>{b.textContent='✓ 下载链接已准备';b.disabled=true})); document.querySelector('[data-all]')?.addEventListener('click',()=>{state.category='全部分类';state.query='';render()}); document.querySelector('[data-upload]')?.addEventListener('click',()=>alert('静态演示版本暂不提供上传。接入后端后可在这里提交资源。')) }
boot()
